---
- include_tasks:        '../tasks/dependencies.yml'
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/create_files.yml'
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/sync_dirs.yml'
- include_tasks:        '../tasks/template_files.yml'
- include_tasks:        '../tasks/symlinks.yml'
- include_tasks:        '../tasks/restart_services.yml'
  when:                 install_files_result.changed
                        or sync_dirs_result.changed
                        or template_files_result.changed
                        or symlinks_result.changed
- include_tasks:        '../tasks/known_hosts.yml'
